"""
PDDLStream Executor with Replanning for Semantic Boxel TAMP.

Executes plans generated by PDDLStream, handling sensing actions with
optimistic planning and replanning when observations don't match expectations.

Key Pattern:
  1. Plan optimistically (assume sensing will find target)
  2. Execute until sensing action
  3. Perform sensing in real world (PyBullet)
  4. If found: continue plan
  5. If not found: update state and REPLAN
"""

import time
import numpy as np
from typing import List, Tuple, Set, Optional, Callable, Dict
from dataclasses import dataclass, field
from enum import Enum

try:
    import pybullet as p
    PYBULLET_AVAILABLE = True
except ImportError:
    PYBULLET_AVAILABLE = False

from boxel_data import BoxelRegistry, BoxelData, BoxelType
from problem_generator import ProblemGenerator, PlanningProblem
from streams import BoxelStreams, RobotConfig, Trajectory, Grasp


class ActionResult(Enum):
    """Result of executing an action."""
    SUCCESS = "success"           # Action completed as planned
    SENSING_MISMATCH = "mismatch" # Sensing result differs from plan
    FAILURE = "failure"           # Action failed (collision, etc.)


@dataclass
class ExecutionState:
    """Current state of plan execution."""
    problem: PlanningProblem
    current_config: str
    holding: Optional[str] = None
    actions_executed: int = 0
    replans: int = 0


class BoxelExecutor:
    """
    Executes PDDLStream plans with sensing and replanning.
    
    Uses optimistic planning: the planner assumes sensing will succeed.
    During execution, if sensing fails (object not found), the executor
    updates the belief state and triggers replanning.
    
    Can optionally control a real PyBullet robot for execution.
    """
    
    # Franka Panda constants
    ARM_JOINT_INDICES = [0, 1, 2, 3, 4, 5, 6]
    FINGER_JOINTS = [9, 10]
    FINGER_OPEN = 0.04
    FINGER_CLOSED = 0.01
    
    def __init__(self, 
                 registry: BoxelRegistry,
                 oracle_locations: dict,
                 planner_fn: Callable[[PlanningProblem], List] = None,
                 robot_id: int = None,
                 physics_client: int = None,
                 config_lookup: Dict[str, np.ndarray] = None,
                 execute_real: bool = False,
                 verbose: bool = True):
        """
        Initialize executor.
        
        Args:
            registry: BoxelRegistry containing scene boxels
            oracle_locations: Dict mapping object_name -> boxel_id (ground truth)
            planner_fn: Function that takes PlanningProblem and returns action list
                        If None, uses mock planner for testing
            robot_id: PyBullet body ID of the robot (for real execution)
            physics_client: PyBullet physics client ID
            config_lookup: Dict mapping config names to joint arrays
            execute_real: If True, actually move robot in PyBullet
            verbose: Print execution trace
        """
        self.registry = registry
        self.oracle_locations = oracle_locations
        self.planner_fn = planner_fn or self._mock_planner
        self.verbose = verbose
        
        # PyBullet robot control
        self.robot_id = robot_id
        self.physics_client = physics_client if physics_client is not None else 0
        self.config_lookup = config_lookup or {}
        self.execute_real = execute_real and PYBULLET_AVAILABLE and robot_id is not None
        
        # Home configuration
        self.home_joints = np.array([0, -0.785, 0, -2.356, 0, 1.571, 0.785])
        self.config_lookup['q_home'] = self.home_joints
        
        self.problem_generator = ProblemGenerator(registry)
        self.streams = BoxelStreams(registry, robot_id=robot_id, physics_client=physics_client)
    
    def execute(self, 
                target_objects: List[str],
                goal: str,
                max_replans: int = 10) -> bool:
        """
        Execute planning and execution loop until goal achieved.
        
        Args:
            target_objects: Objects to reason about
            goal: Goal specification (e.g., "(holding target_1)")
            max_replans: Maximum number of replanning attempts
            
        Returns:
            True if goal achieved, False if max_replans exceeded
        """
        # Generate initial problem
        problem = self.problem_generator.generate_problem(
            target_objects=target_objects,
            goal=goal
        )
        
        state = ExecutionState(
            problem=problem,
            current_config="q_home"
        )
        
        if self.verbose:
            print("\n" + "="*70)
            print("BOXEL TAMP EXECUTOR - Starting Execution")
            print("="*70)
            print(f"Target objects: {target_objects}")
            print(f"Goal: {goal}")
            self.problem_generator.print_epistemic_state(problem, target_objects)
        
        while state.replans < max_replans:
            # Generate plan
            if self.verbose:
                print(f"\n--- Planning (attempt {state.replans + 1}) ---")
            
            plan = self.planner_fn(state.problem)
            
            if plan is None or len(plan) == 0:
                print("ERROR: No plan found!")
                return False
            
            if self.verbose:
                print(f"Plan generated with {len(plan)} actions:")
                for i, action in enumerate(plan):
                    print(f"  {i+1}. {action}")
            
            # Execute plan
            for action in plan:
                result = self._execute_action(action, state, target_objects)
                state.actions_executed += 1
                
                if result == ActionResult.SUCCESS:
                    if self.verbose:
                        print(f"  [OK] {action[0]} succeeded")
                    continue
                    
                elif result == ActionResult.SENSING_MISMATCH:
                    if self.verbose:
                        print(f"  [REPLAN] Sensing mismatch - triggering replan")
                        self.problem_generator.print_epistemic_state(
                            state.problem, target_objects)
                    state.replans += 1
                    break  # Exit action loop, regenerate plan
                    
                else:  # FAILURE
                    print(f"  [FAIL] Action failed: {action}")
                    return False
            else:
                # Plan completed successfully (no break)
                if self._goal_achieved(state, goal):
                    if self.verbose:
                        print("\n" + "="*70)
                        print("SUCCESS! Goal achieved.")
                        print(f"  Actions executed: {state.actions_executed}")
                        print(f"  Replans needed: {state.replans}")
                        print("="*70)
                    return True
        
        print(f"ERROR: Max replans ({max_replans}) exceeded")
        return False
    
    def _execute_action(self, action: Tuple, state: ExecutionState,
                        target_objects: List[str]) -> ActionResult:
        """
        Execute a single action.
        
        Args:
            action: Tuple of (action_name, *parameters)
            state: Current execution state
            target_objects: Objects being reasoned about
            
        Returns:
            ActionResult indicating success, mismatch, or failure
        """
        name = action[0]
        params = action[1:] if len(action) > 1 else []
        
        if name == "sense_boxel":
            return self._execute_sense(params, state, target_objects)
        elif name == "move":
            return self._execute_move(params, state)
        elif name == "pick":
            return self._execute_pick(params, state)
        elif name == "place":
            return self._execute_place(params, state)
        else:
            print(f"Unknown action: {name}")
            return ActionResult.FAILURE
    
    def _execute_sense(self, params: Tuple, state: ExecutionState,
                       target_objects: List[str]) -> ActionResult:
        """
        Execute sensing action with belief update.
        
        Uses oracle to determine actual observation result.
        Updates epistemic state and checks for mismatch.
        """
        obj_name, boxel_id, config = params
        
        if self.verbose:
            print(f"  -> Sensing {boxel_id} for {obj_name}...")
        
        # Oracle: Is the object actually in this boxel?
        actual_location = self.oracle_locations.get(obj_name)
        found = (actual_location == boxel_id)
        
        if self.verbose:
            result_str = "FOUND!" if found else "not found"
            print(f"    Observation: {result_str}")
        
        # Update belief state
        state.problem = self.problem_generator.update_after_sensing(
            state.problem, obj_name, boxel_id, found
        )
        
        # Plan assumed object would be found (optimistic)
        # If not found, we have a mismatch and need to replan
        if not found:
            return ActionResult.SENSING_MISMATCH
        
        return ActionResult.SUCCESS
    
    def _execute_move(self, params: Tuple, state: ExecutionState) -> ActionResult:
        """Execute motion action."""
        q1, q2, traj = params
        
        if self.verbose:
            print(f"  -> Moving from {q1} to {q2}")
        
        # Update state
        state.current_config = q2
        
        # Execute real motion if enabled
        if self.execute_real:
            target_joints = self._get_config_joints(q2)
            if target_joints is not None:
                self._move_robot_to_config(target_joints)
        else:
            time.sleep(0.1)  # Simulate execution time
        
        return ActionResult.SUCCESS
    
    def _get_config_joints(self, config_name: str) -> Optional[np.ndarray]:
        """Get joint positions for a named configuration."""
        if config_name in self.config_lookup:
            return self.config_lookup[config_name]
        return None
    
    def _move_robot_to_config(self, target_joints: np.ndarray, 
                              duration: float = 1.0, max_steps: int = 500,
                              tolerance: float = 0.05):
        """
        Move robot to target joint configuration.
        
        Args:
            target_joints: Target joint positions (7 DOF)
            duration: Minimum time to complete motion in seconds
            max_steps: Maximum simulation steps
            tolerance: Joint error tolerance for convergence
        """
        if not PYBULLET_AVAILABLE or self.robot_id is None:
            return
        
        # Set target for all joints
        for j, joint_idx in enumerate(self.ARM_JOINT_INDICES):
            p.setJointMotorControl2(
                self.robot_id,
                joint_idx,
                p.POSITION_CONTROL,
                targetPosition=target_joints[j],
                force=240,
                maxVelocity=2.0,
                physicsClientId=self.physics_client
            )
        
        # Step simulation until converged or max steps reached
        dt = 1.0 / 240.0
        for step in range(max_steps):
            p.stepSimulation(physicsClientId=self.physics_client)
            
            # Check convergence every 10 steps
            if step % 10 == 0 and step > 0:
                current_joints = np.array([
                    p.getJointState(self.robot_id, i, physicsClientId=self.physics_client)[0]
                    for i in self.ARM_JOINT_INDICES
                ])
                error = np.max(np.abs(current_joints - target_joints))
                if error < tolerance:
                    break
            
            # Sleep to maintain real-time (optional, slows down but looks better in GUI)
            # time.sleep(dt)
    
    def _open_gripper(self):
        """Open the robot gripper."""
        if not PYBULLET_AVAILABLE or self.robot_id is None:
            return
        for finger_idx in self.FINGER_JOINTS:
            p.setJointMotorControl2(
                self.robot_id,
                finger_idx,
                p.POSITION_CONTROL,
                targetPosition=self.FINGER_OPEN,
                force=20,
                physicsClientId=self.physics_client
            )
        for _ in range(50):
            p.stepSimulation(physicsClientId=self.physics_client)
            time.sleep(1/240)
    
    def _close_gripper(self):
        """Close the robot gripper."""
        if not PYBULLET_AVAILABLE or self.robot_id is None:
            return
        for finger_idx in self.FINGER_JOINTS:
            p.setJointMotorControl2(
                self.robot_id,
                finger_idx,
                p.POSITION_CONTROL,
                targetPosition=self.FINGER_CLOSED,
                force=20,
                physicsClientId=self.physics_client
            )
        for _ in range(50):
            p.stepSimulation(physicsClientId=self.physics_client)
            time.sleep(1/240)
    
    def _execute_pick(self, params: Tuple, state: ExecutionState) -> ActionResult:
        """Execute pick action."""
        obj_name, boxel_id, grasp, config = params
        
        if self.verbose:
            print(f"  -> Picking {obj_name} from {boxel_id}")
        
        # Execute real pick if enabled
        if self.execute_real:
            # Move to pick config
            target_joints = self._get_config_joints(config)
            if target_joints is not None:
                self._open_gripper()
                self._move_robot_to_config(target_joints)
                self._close_gripper()
        else:
            time.sleep(0.1)
        
        # Update state
        state.holding = obj_name
        
        return ActionResult.SUCCESS
    
    def _execute_place(self, params: Tuple, state: ExecutionState) -> ActionResult:
        """Execute place action."""
        obj_name, boxel_id, grasp, config = params
        
        if self.verbose:
            print(f"  -> Placing {obj_name} in {boxel_id}")
        
        # Execute real place if enabled
        if self.execute_real:
            target_joints = self._get_config_joints(config)
            if target_joints is not None:
                self._move_robot_to_config(target_joints)
                self._open_gripper()
        else:
            time.sleep(0.1)
        
        # Update state
        state.holding = None
        
        return ActionResult.SUCCESS
    
    def _goal_achieved(self, state: ExecutionState, goal: str) -> bool:
        """Check if goal is achieved."""
        # Simple check for common goals
        if "holding" in goal:
            # Extract object name from goal like "(holding target_1)"
            obj_name = goal.replace("(", "").replace(")", "").split()[1]
            return state.holding == obj_name
        return False
    
    def _mock_planner(self, problem: PlanningProblem) -> List[Tuple]:
        """
        Mock planner for testing without PDDLStream.
        
        Generates a simple plan that senses shadows in order until
        it finds one where the target COULD be (KIF=false).
        """
        # Find target object
        target = None
        for obj_str in problem.objects:
            if " - obj" in obj_str:
                target = obj_str.split()[0]
                break
        
        if target is None:
            return []
        
        # Find shadow boxels that haven't been sensed yet
        unsensed_shadows = []
        for obj_str in problem.objects:
            if " - boxel" in obj_str:
                boxel_id = obj_str.split()[0]
                if f"(is_shadow {boxel_id})" in problem.init:
                    kif_fact = f"(obj_at_boxel_KIF {target} {boxel_id})"
                    if kif_fact not in problem.init:
                        unsensed_shadows.append(boxel_id)
        
        if not unsensed_shadows:
            # All shadows sensed, check if we know where target is
            for obj_str in problem.objects:
                if " - boxel" in obj_str:
                    boxel_id = obj_str.split()[0]
                    if f"(obj_at_boxel {target} {boxel_id})" in problem.init:
                        # Found it! Generate pick plan
                        return [
                            ("move", "q_home", f"q_pick_{boxel_id}", "traj_1"),
                            ("pick", target, boxel_id, "grasp_1", f"q_pick_{boxel_id}")
                        ]
            return []  # Can't find target
        
        # Sense first unsensed shadow
        shadow_to_sense = unsensed_shadows[0]
        return [
            ("move", "q_home", f"q_sense_{shadow_to_sense}", "traj_1"),
            ("sense_boxel", target, shadow_to_sense, f"q_sense_{shadow_to_sense}"),
            # Optimistically assume found, then pick
            ("move", f"q_sense_{shadow_to_sense}", f"q_pick_{shadow_to_sense}", "traj_2"),
            ("pick", target, shadow_to_sense, "grasp_1", f"q_pick_{shadow_to_sense}")
        ]


def demo_execution(registry: BoxelRegistry, 
                   target_location: str = "shadow_001") -> bool:
    """
    Demonstrate the executor with a simple hidden object scenario.
    
    Args:
        registry: BoxelRegistry from the scene
        target_location: Boxel ID where target is actually hidden
        
    Returns:
        True if execution succeeded
    """
    print("\n" + "#"*70)
    print("# DEMONSTRATION: Hidden Object Search with Replanning")
    print("#"*70)
    print(f"\nScenario: target_1 is hidden in {target_location}")
    print("The robot must sense shadow boxels to find it.\n")
    
    # Ground truth: target is in specified shadow
    oracle_locations = {
        "target_1": target_location
    }
    
    executor = BoxelExecutor(
        registry=registry,
        oracle_locations=oracle_locations,
        verbose=True
    )
    
    success = executor.execute(
        target_objects=["target_1"],
        goal="(holding target_1)",
        max_replans=10
    )
    
    return success
