#!/usr/bin/env python3
"""
Tests for BoxelStreams: IK correctness, stream output format, math utilities,
cap mechanism, and a reachability diagnostic report.

Run from WSL:
    source wsl_env/bin/activate
    pytest test_streams.py -v -s
"""

import os
import sys
import math
import numpy as np
import pybullet as p
import pybullet_data
import pytest

from streams import BoxelStreams, RobotConfig, Trajectory, Grasp
from boxel_data import BoxelRegistry, BoxelData, BoxelType


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="module")
def pybullet_env():
    """Headless PyBullet with Franka Panda on a plane (shared across module)."""
    client = p.connect(p.DIRECT)
    p.setAdditionalSearchPath(pybullet_data.getDataPath())
    p.setGravity(0, 0, -9.8, physicsClientId=client)

    p.loadURDF("plane.urdf", [0, 0, 0], physicsClientId=client)
    robot_id = p.loadURDF(
        "franka_panda/panda.urdf", [0, 0, 0], useFixedBase=True,
        physicsClientId=client,
    )
    yield {"client": client, "robot_id": robot_id}
    p.disconnect(client)


@pytest.fixture(scope="module")
def registry():
    """Load BoxelRegistry from boxel_data.json (generated by the pipeline)."""
    json_path = os.path.join(os.path.dirname(__file__), "boxel_data.json")
    if not os.path.exists(json_path):
        pytest.skip("boxel_data.json not found — run test_full_pipeline.py first")
    return BoxelRegistry.load_from_json(json_path)


@pytest.fixture(scope="module")
def streams(pybullet_env, registry):
    """BoxelStreams wired to the headless Panda."""
    return BoxelStreams(
        registry,
        robot_id=pybullet_env["robot_id"],
        physics_client=pybullet_env["client"],
    )


# ===========================================================================
# 1. Dataclass hash / eq / repr
# ===========================================================================

class TestDataclasses:

    def test_robot_config_hashable(self):
        c1 = RobotConfig(joint_positions=np.zeros(7), name="q1")
        c2 = RobotConfig(joint_positions=np.ones(7), name="q1")
        assert hash(c1) == hash(c2)
        assert c1 == c2
        assert len({c1, c2}) == 1

    def test_robot_config_different_names(self):
        c1 = RobotConfig(joint_positions=np.zeros(7), name="a")
        c2 = RobotConfig(joint_positions=np.zeros(7), name="b")
        assert c1 != c2
        assert len({c1, c2}) == 2

    def test_robot_config_repr(self):
        c = RobotConfig(joint_positions=np.zeros(7), name="q_home")
        assert repr(c) == "q_home"

    def test_grasp_hashable(self):
        g1 = Grasp(np.zeros(3), np.array([0, 0, 0, 1]), name="g1")
        g2 = Grasp(np.ones(3), np.array([1, 0, 0, 0]), name="g1")
        assert g1 == g2
        assert len({g1, g2}) == 1

    def test_grasp_repr(self):
        g = Grasp(np.zeros(3), np.array([0, 0, 0, 1]), name="grasp_A")
        assert repr(g) == "grasp_A"

    def test_trajectory_hashable(self):
        t1 = Trajectory(waypoints=[], name="t1")
        t2 = Trajectory(waypoints=[RobotConfig(np.zeros(7))], name="t1")
        assert t1 == t2
        assert len({t1, t2}) == 1

    def test_trajectory_repr(self):
        t = Trajectory(waypoints=[None, None, None], name="traj_3")
        assert repr(t) == "traj_3"

    def test_eq_returns_not_implemented_for_foreign_type(self):
        c = RobotConfig(joint_positions=np.zeros(7), name="x")
        assert c.__eq__("not a config") is NotImplemented


# ===========================================================================
# 2. Math utilities
# ===========================================================================

class TestMathUtils:

    @pytest.fixture(autouse=True)
    def _make_streams(self):
        """Minimal BoxelStreams with no robot (math helpers don't need one)."""
        dummy_reg = BoxelRegistry()
        self.s = BoxelStreams(dummy_reg, robot_id=None, physics_client=None)

    def test_direction_to_quat_unit(self):
        for d in [np.array([0, 0, -1.0]),
                  np.array([1, 0, 0.0]),
                  np.array([0.3, -0.7, 0.5])]:
            q = self.s._direction_to_quat(d / np.linalg.norm(d))
            assert abs(np.linalg.norm(q) - 1.0) < 1e-6, f"non-unit quat for dir={d}"

    def test_rotation_matrix_to_quat_identity(self):
        R = np.eye(3)
        q = self.s._rotation_matrix_to_quat(R)
        assert abs(np.linalg.norm(q) - 1.0) < 1e-6
        # Identity rotation -> quat [0,0,0,1]
        assert abs(q[3]) > 0.99, f"expected w≈1 for identity, got {q}"

    def test_rotation_matrix_to_quat_90z(self):
        """90-degree rotation about Z."""
        R = np.array([[0, -1, 0],
                      [1,  0, 0],
                      [0,  0, 1]], dtype=float)
        q = self.s._rotation_matrix_to_quat(R)
        assert abs(np.linalg.norm(q) - 1.0) < 1e-6
        # Expected: [0, 0, sin(45°), cos(45°)] = [0, 0, 0.7071, 0.7071]
        assert abs(abs(q[2]) - math.sin(math.pi / 4)) < 1e-4
        assert abs(abs(q[3]) - math.cos(math.pi / 4)) < 1e-4

    def test_euler_to_quat_matches_pybullet(self):
        """Compare our Euler->quat with PyBullet's reference implementation."""
        for roll, pitch, yaw in [(0, 0, 0), (0, math.pi, 0),
                                  (0.1, -0.3, 1.2), (math.pi/2, 0, math.pi/4)]:
            ours = self.s._euler_to_quat(roll, pitch, yaw)
            ref = np.array(p.getQuaternionFromEuler([roll, pitch, yaw]))
            assert np.allclose(ours, ref, atol=1e-6), \
                f"euler ({roll},{pitch},{yaw}): ours={ours} ref={ref}"


# ===========================================================================
# 3. IK tests (need PyBullet + Panda)
# ===========================================================================

class TestIK:

    def test_reachable_position(self, streams, pybullet_env):
        """A position in front of and above the robot base should be reachable."""
        ee_pos = np.array([0.5, 0.0, 0.5])
        ee_orn = np.array(p.getQuaternionFromEuler([0, math.pi, 0]))
        config = streams._pybullet_ik(ee_pos, ee_orn)

        assert config is not None, "IK returned None for a reachable target"
        assert config.joint_positions.shape == (7,)
        # Joint limits
        assert np.all(config.joint_positions >= streams.joint_limits_low - 0.01)
        assert np.all(config.joint_positions <= streams.joint_limits_high + 0.01)

    def test_fk_matches_target(self, streams, pybullet_env):
        """FK of the returned joints should be within 5 cm of the request."""
        ee_pos = np.array([0.4, 0.1, 0.4])
        ee_orn = np.array(p.getQuaternionFromEuler([0, math.pi, 0]))
        config = streams._pybullet_ik(ee_pos, ee_orn)
        if config is None:
            pytest.skip("IK didn't converge for this target — acceptable")

        client = pybullet_env["client"]
        robot = pybullet_env["robot_id"]
        state_id = p.saveState(physicsClientId=client)
        for i in range(7):
            p.resetJointState(robot, i, config.joint_positions[i],
                              physicsClientId=client)
        actual = np.array(p.getLinkState(robot, 11,
                                          physicsClientId=client)[0])
        p.restoreState(state_id, physicsClientId=client)
        p.removeState(state_id, physicsClientId=client)

        error = np.linalg.norm(actual - ee_pos)
        assert error < 0.08, f"FK error {error:.4f} m exceeds 8 cm threshold"

    def test_unreachable_position(self, streams):
        """A target far outside the workspace should return None."""
        ee_pos = np.array([5.0, 5.0, 5.0])
        ee_orn = np.array([0, 0, 0, 1])
        assert streams._pybullet_ik(ee_pos, ee_orn) is None


# ===========================================================================
# 4. Stream output format
# ===========================================================================

class TestStreamFormat:

    def test_sample_push_config_format(self, streams, registry):
        occluders = [b.id for b in registry.boxels.values()
                     if b.boxel_type == BoxelType.OBJECT]
        if not occluders:
            pytest.skip("No occluders in registry")

        results = list(streams.sample_push_config(occluders[0]))
        assert len(results) >= 1, "Expected at least 1 push config"
        for r in results:
            assert isinstance(r, tuple) and len(r) == 1
            assert isinstance(r[0], RobotConfig)
            assert r[0].name, "name must be non-empty"

    def test_sample_sensing_config_format(self, streams, registry):
        shadows = [b.id for b in registry.boxels.values()
                   if b.boxel_type == BoxelType.SHADOW]
        if not shadows:
            pytest.skip("No shadows in registry")

        results = list(streams.sample_sensing_config(shadows[0]))
        assert len(results) >= 1, "Expected at least 1 sensing config"
        for r in results:
            assert isinstance(r, tuple) and len(r) == 1
            assert isinstance(r[0], RobotConfig)
            assert r[0].name

    def test_sample_grasp_format(self, streams):
        results = list(streams.sample_grasp("any_object"))
        assert len(results) == 4, f"Expected 4 grasps, got {len(results)}"
        for r in results:
            assert isinstance(r, tuple) and len(r) == 1
            assert isinstance(r[0], Grasp)
            assert r[0].name
            assert abs(np.linalg.norm(r[0].orientation) - 1.0) < 1e-6

    def test_plan_motion_format(self, streams):
        q1 = RobotConfig(np.zeros(7), name="q_a")
        q2 = RobotConfig(np.ones(7) * 0.1, name="q_b")
        results = list(streams.plan_motion(q1, q2))
        assert len(results) == 1
        traj = results[0][0]
        assert isinstance(traj, Trajectory)
        assert len(traj.waypoints) == 10
        assert traj.name

    def test_compute_kin_format(self, streams, registry):
        shadows = [b.id for b in registry.boxels.values()
                   if b.boxel_type == BoxelType.SHADOW]
        if not shadows:
            pytest.skip("No shadows in registry")
        grasp = Grasp(np.array([0, 0, 0.05]),
                      np.array([0, 0, 0, 1]), name="test_g")
        results = list(streams.compute_kin_solution("obj_test", shadows[0], grasp))
        # May be 0 if IK fails for this boxel — that's fine
        for r in results:
            assert isinstance(r, tuple) and len(r) == 1
            assert isinstance(r[0], RobotConfig)
            assert r[0].name

    def test_nonexistent_boxel_yields_nothing(self, streams):
        assert list(streams.sample_push_config("nonexistent_boxel")) == []
        assert list(streams.sample_sensing_config("nonexistent_boxel")) == []
        grasp = Grasp(np.zeros(3), np.array([0, 0, 0, 1]), name="g")
        assert list(streams.compute_kin_solution("o", "nonexistent_boxel", grasp)) == []


# ===========================================================================
# 5. Stream logging wrapper
# ===========================================================================

class TestStreamLogging:

    def test_logged_counts_results(self):
        """_logged wrapper tracks call count and result count."""
        from pddlstream_planner import PDDLStreamPlanner
        from boxel_data import BoxelRegistry

        planner = PDDLStreamPlanner(BoxelRegistry())
        planner._init_stream_stats()

        def gen(x):
            yield ("a",)
            yield ("b",)

        logged = planner._logged('sample-grasp', gen)
        results = list(logged("obj1"))
        assert len(results) == 2
        assert planner._stream_stats['sample-grasp']['calls'] == 1
        assert planner._stream_stats['sample-grasp']['results'] == 2

    def test_logged_does_not_cap(self):
        """_logged passes through all results without capping."""
        from pddlstream_planner import PDDLStreamPlanner
        from boxel_data import BoxelRegistry

        planner = PDDLStreamPlanner(BoxelRegistry())
        planner._init_stream_stats()

        def gen(x):
            for i in range(20):
                yield (i,)

        logged = planner._logged('sample-grasp', gen)
        results = list(logged("test"))
        assert len(results) == 20


# ===========================================================================
# 6. Reachability report (diagnostic, always passes)
# ===========================================================================

def test_reachability_report(streams, registry, capsys):
    """
    Diagnostic: for every occluder and shadow, try the streams and report
    how many IK solutions pass FK verification. This always 'passes' but
    prints a table useful for debugging planning failures.
    """
    print("\n" + "=" * 70)
    print("REACHABILITY REPORT  (FK-verified IK solutions per boxel)")
    print("=" * 70)

    occluders = sorted(b.id for b in registry.boxels.values()
                       if b.boxel_type == BoxelType.OBJECT)
    shadows = sorted(b.id for b in registry.boxels.values()
                     if b.boxel_type == BoxelType.SHADOW)

    print(f"\n{'Boxel ID':<16} {'Type':<10} {'Center':^30} {'IK OK':>6} {'IK Tried':>9}")
    print("-" * 70)

    total_ok, total_tried = 0, 0

    for occ_id in occluders:
        boxel = registry.get_boxel(occ_id)
        center = boxel.center
        results = list(streams.sample_push_config(occ_id))
        ok = len(results)
        tried = 4  # 4 angles attempted
        total_ok += ok
        total_tried += tried
        print(f"{occ_id:<16} {'occluder':<10} [{center[0]:.2f}, {center[1]:.2f}, {center[2]:.2f}]"
              f"{'':>6}{ok:>6} / {tried}")

    for shd_id in shadows:
        boxel = registry.get_boxel(shd_id)
        center = boxel.center
        results = list(streams.sample_sensing_config(shd_id))
        ok = len(results)
        tried = 8 * 3  # 8 angles x 3 heights
        total_ok += ok
        total_tried += tried
        print(f"{shd_id:<16} {'shadow':<10} [{center[0]:.2f}, {center[1]:.2f}, {center[2]:.2f}]"
              f"{'':>6}{ok:>6} / {tried}")

    print("-" * 70)
    print(f"{'TOTAL':<16} {'':10} {'':30} {total_ok:>6} / {total_tried}")
    if total_tried > 0:
        print(f"Overall FK-verified success rate: {100*total_ok/total_tried:.1f}%")
    print("=" * 70)
