;; =============================================================================
;; SEMANTIC BOXEL TAMP PROBLEM TEMPLATE
;; =============================================================================
;; This is a template showing the structure of a problem file.
;; The actual problem is generated dynamically from BoxelRegistry.
;; =============================================================================

(define (problem find-and-pick-target)
  (:domain boxel-tamp)
  
  ;; =========================================================================
  ;; OBJECTS
  ;; =========================================================================
  (:objects
    ;; Boxels (generated from BoxelRegistry)
    obj_006 obj_007 obj_008 obj_009 - boxel           ;; Object boxels
    shadow_000 shadow_001 shadow_002 - boxel          ;; Shadow boxels
    
    ;; Manipulable objects
    target_1 - obj
    
    ;; Configurations (generated by streams)
    q_home - config
  )
  
  ;; =========================================================================
  ;; INITIAL STATE
  ;; =========================================================================
  (:init
    ;; --- Boxel Structure ---
    (semantic_zone obj_006)
    (semantic_zone obj_007)
    (semantic_zone shadow_000)
    (semantic_zone shadow_001)
    (is_object_boxel obj_006)
    (is_object_boxel obj_007)
    (is_shadow shadow_000)
    (is_shadow shadow_001)
    (occludes obj_006 shadow_000)
    (occludes obj_007 shadow_001)
    
    ;; --- Object Properties ---
    (obj_graspable target_1)
    
    ;; --- Ground Truth (HIDDEN FROM PLANNER in real execution) ---
    ;; In simulation, we know target_1 is in shadow_001
    ;; But planner doesn't know this initially!
    ;; (obj_at_boxel target_1 shadow_001)  ;; <-- Would be set by world, not init
    
    ;; --- Epistemic State (What the robot KNOWS) ---
    ;; Initially: we DON'T know where target is in shadows
    ;; (obj_at_boxel_KIF target_1 shadow_000) = FALSE (not listed)
    ;; (obj_at_boxel_KIF target_1 shadow_001) = FALSE (not listed)
    
    ;; For object boxels, we KNOW they don't contain the target
    (obj_at_boxel_KIF target_1 obj_006)   ;; We checked: target not in occluder
    (obj_at_boxel_KIF target_1 obj_007)
    ;; Note: obj_at_boxel NOT listed = we know it's NOT there (KIF=true, at=false)
    
    ;; --- Robot State ---
    (at_config q_home)
    (handempty)
  )
  
  ;; =========================================================================
  ;; GOAL
  ;; =========================================================================
  (:goal
    (holding target_1)
  )
)
